Application:
  Devices:
  - MOPS
  app_icon_dir: mopshubGUI/icons/icon_mops.png
  app_name: CANMOPS
  app_version: v1.2
  user: Ahmed Qamesh
  multi_mode: False
  mopshub_mode: True
  mopshub_communication_mode: UHAL
  trim_mode: True
  refresh_rate: 500 #in ms
  wait_time: 0.0 #in s
channel_ports:
  "0":
  "1":
