state_machines:
  sm_items:
    '0':
      sm_name: main_sm
      file_name: can_elink_bridge_sm_fsm
      sm_subindex_items:
        '0': ST_reset
        '1': ST_initial
        '2': ST_waittoact
        '3': ST_endwait
        '4': ST_signon
        '5': ST_rst_all_can
        '6': ST_init_Trim
        '7': ST_start_read_elink
        '8': ST_write_can
        '9': ST_send_can
        '10': ST_rst_can_tra
        '11': ST_end_read_can
        '12': ST_rst_can_rec
        '13': ST_write_elink
        '14': ST_start_read_can
        '15': ST_read_can
        '16': ST_abort
        '17': ST_init_Mon
        '18': ST_Wait_can_sm
        '19': ST_end_read_elink
        '20': ST_end_write_elink
      description_items: 'The Main State Machine           '
    '1':
      sm_name: can_interface_sm
      file_name: can_interface_sm_fsm
      sm_subindex_items:
        '0': ST_waittoact
        '1': ST_reset
        '2': ST_prescalar
        '3': ST_general
        '4': ST_encom
        '5': ST_accmask_cs
        '6': accmask1
        '7': ST_idr3_cs
        '8': ST_idr41_cs
        '9': ST_endinit
        '10': ST_start_init
        '11': ST_wait_can
        '12': RB1
        '13': store_RB1
        '14': store_idr1
        '15': idr1
        '16': RB2
        '17': store_RB2
        '18': RB3
        '19': RB4
        '20': store_RB3
        '21': end_readst
        '22': store_RB4
        '23': set_d3
        '24': set_d1
        '25': set_gen
        '26': ST_rstirq
        '27': ST_general1
        '28': ST_rstirq_n
        '29': ST_general_cs_n
        '30': ST_start
        '31': ST_countrst_n
        '32': ST_loop_rst
        '33': ST_start_cnt
        '34': ST_finish_trim
        '35': ST_start_trim
        '36': ST_general_t
        '37': ST_id_t
        '38': ST_data1_t
        '39': ST_data2_t
        '40': d7
        '41': d8
        '42': tc1
        '43': set_id1
        '44': set_tc
        '45': set_d4
        '46': set_d2
        '47': Set_bus_Id2
        '48': Wait_bits
        '49': ST_prescal_CS
        '50': ST_general_cs
        '51': ST_encom_cs
        '52': ST_idr3
        '53': ST_idr4
        '54': ST_accmask
        '55': ST_accmaskcs
        '56': ST_general1_cs
        '57': ST_rstirq_cs
        '58': set_gen1
        '59': set_id2
        '60': set_tc1
        '61': set_d5
        '62': set_d6
        '63': set_d7
        '64': set_d8
        '65': ST_general_n
        '66': ST_rstirq_cs_n
        '67': ST_general_cs_t
        '68': ST_id_cs_t
        '69': ST_data1_cs_t
        '70': d10
        '71': d11
        '72': d12
        '73': tc2
      description_items: 'The CAN Interface State Machine  '
    '2':
      sm_name: can_mux_sm
      file_name: bus_rec_sm_fsm
      sm_subindex_items:
        '0': ST_bus_loop
        '1': ST_reset_loop
        '2': ST_reset
        '3': ST_Done
        '4': ST_waittoact
        '5': ST_read_irq
        '6': canbus1
        '7': donebus1
        '8': canbus2
        '9': donebus2
        '10': canbus3
        '11': donebus32
        '12': canbus4
        '13': donebus4
        '14': canbus5
        '15': donebus5
        '16': canbus6
        '17': donebus6
        '18': canbus7
        '19': donebus7
        '20': canbus8
        '21': donebus8
        '22': canbus9
        '23': donebus9
        '24': canbus10
        '25': donebus10
        '26': canbus11
        '27': donebus11
        '28': canbus12
        '29': donebus12
        '30': canbus13
        '31': donebus13
        '32': canbus14
        '33': donebus14
        '34': canbus15
        '35': donebus15
        '36': canbus0
        '37': donebus0
        '38': canbus16
        '39': donebus16
        '40': canbus17
        '41': donebus17
        '42': canbus18
        '43': donebus18
        '44': canbus19
        '45': donebus19
        '46': canbus20
        '47': donebus20
        '48': canbus21
        '49': donebus21
        '50': canbus22
        '51': donebus22
        '52': canbus23
        '53': donebus23
        '54': canbus24
        '55': donebus24
        '56': canbus25
        '57': donebus25
        '58': canbus26
        '59': donebus26
        '60': canbus27
        '61': donebus27
        '62': canbus28
        '63': donebus28
        '64': canbus29
        '65': donebus29
        '66': canbus30
        '67': donebus30
        '68': canbus31
        '69': donebus31
      description_items: 'The CAN Mux State Machine        '
    '3':
      sm_name: osc_sm
      file_name: osc_trim_sm_fsm
      sm_subindex_items:
        '0': ST_waittoact
        '1': ST_reset
        '2': ST_Skip_bus
        '3': rst_irq_can
        '4': Wait_W_SPI2
        '5': ST_Start_Cnt
        '6': Break_Loop
        '7': finish_proc
        '8': ST_CountRst
        '9': Check_Trim
        '10': ST_Done_Trim
        '11': ST_En_power1
        '12': Wait_W_SPI1
        '13': ST_MOPS_dbg2
        '14': ST_Bus_enable
        '15': ST_Bus_enable0
        '16': Wait_W_SPI0
        '17': Read_Resp
        '18': pass_to_elink
        '19': Wait_Resp
        '20': rst_rec_irq_can
        '21': finish_proc1
        '22': rst_tra_irq_can
        '23': Trim_ack
        '24': Start_write_trim
        '25': pass_mes_to_can
        '26': send_ack1
        '27': Wait_foR_sm
        '28': RST_MOPS_dbg1
        '29': Break_Loop1
        '30': finish_proc3
        '31': Check_Trim1
        '32': ST_Done_Trim1
        '33': ST_En_power2
        '34': Wait_W_SPI3
        '35': Read_Resp1
        '36': pass_to_elink1
        '37': Wait_Resp1
        '38': rst_rec_irq_can1
        '39': finish_proc2
        '40': rst_tra_irq_can1
        '41': Trim_ack1
        '42': Start_write_trim1
        '43': pass_mes_to_can1
        '44': send_ack2
      description_items: The Trim Oscillator State Machine
    '4':
      sm_name: elink_tra_sm
      file_name: elink_interface_tra_sm_fsm
      sm_subindex_items:
        '0': ST_waittoact
        '1': ST_reset
        '2': ST_end_write_en
        '3': store_WB0
        '4': store_WB1
        '5': ST_wait_can_rq
        '6': store_WB8
        '7': store_WB2
        '8': store_WB7
        '9': store_WB3
        '10': store_WB6
        '11': store_WB4
        '12': store_WB5
        '13': st_write_data
        '14': store_SOP
        '15': store_WB9
        '16': store_Eop
        '17': WB0
        '18': WB1
        '19': WB2
        '20': WB3
        '21': WB4
        '22': WB5
        '23': WB6
        '24': WB7
        '25': WB8
        '26': WB9
        '27': W_SOP
        '28': W_Eop
        '29': ST_end_write_en_SPI
        '30': store_SPI0
        '31': store_SPI1
        '32': ST_wait_can_rq_SPI
        '33': store_SPI2
        '34': store_SPI3
        '35': st_write_data_SPI
        '36': store_SOP_SPI
        '37': store_Eop1
        '38': SPI0
        '39': SPI1
        '40': SPI2
        '41': SPI3
        '42': W_SOP1
        '43': W_Eop1
        '44': store_Comma
        '45': store_comma1
        '46': ST_end_write_en_DBG
        '47': store_WB0_DBG
        '48': store_WB1_DBG
        '49': ST_wait_can_rq_DBG
        '50': store_WB8_DBG
        '51': store_WB2_DBG
        '52': store_WB7_DBG
        '53': store_WB3_DBG
        '54': store_WB6_DBG
        '55': store_WB4_DBG
        '56': store_WB5_DBG
        '57': st_write_data_DBG
        '58': store_SOP_DBG
        '59': store_WB9_DBG
        '60': Store_Eop_DBG
        '61': WB0_DBG
        '62': WB1_DBG
        '63': WB2_DBG
        '64': WB3_DBG
        '65': WB4_DBG
        '66': WB5_DBG
        '67': WB6_DBG
        '68': WB7_DBG
        '69': WB8_DBG
        '70': WB9_DBG
        '71': W_SOP_DBG
        '72': W_Eop_DBG
        '73': Store_Comma_DBG
        '74': store_WB21
        '75': WB21
        '76': store_WB23
        '77': WB23
        '78': store_WB25
        '79': WB24
        '80': WB25
        '81': store_WB26
        '82': store_WB27
        '83': WB26
        '84': store_WB28
        '85': WB27
        '86': ST_end_write_en_rst
        '87': store_WB0_rst
        '88': store_WB1_rst
        '89': ST_wait_can_rq_rst
        '90': store_WB8_rst
        '91': store_WB2_rst
        '92': store_WB7_rst
        '93': store_WB3_rst
        '94': store_WB6_rst
        '95': store_WB4_rst
        '96': store_WB5_rst
        '97': st_write_data_rst
        '98': store_SOP_rst
        '99': store_WB9_rst
        '100': store_Eop_rst
        '101': WB0_rst
        '102': WB1_rst
        '103': WB2_rst
        '104': WB3_rst
        '105': WB4_rst
        '106': WB5_rst
        '107': WB6_rst
        '108': WB7_rst
        '109': WB8_rst
        '110': WB9_rst
        '111': W_SOP_rst
        '112': W_Eop_rst
        '113': store_comma_rst
        '114': ST_endwait
        '115': W_Comma
        '116': W_Comma_DBG
        '117': W_Comma_rst
        '118': W_Comma3
      description_items: 'The Elink tra State Machine      '
    '5':
      sm_name: elink_rec_sm
      file_name: elink_interface_rec_sm_fsm
      sm_subindex_items:
        '0': ST_waittoact
        '1': ST_reset
        '2': store_RB2
        '3': store_RB3
        '4': store_RB4
        '5': store_RB0
        '6': RB1
        '7': store_RB5
        '8': store_RB6
        '9': store_RB7
        '10': store_RB8
        '11': store_RB9
        '12': ST_wait_eop
        '13': ST_end_read_en
        '14': ST_Wait
        '15': ST_en_buffer
        '16': ST_wait_sop
        '17': RB0
        '18': store_SPI0
        '19': store_SPI1
        '20': store_SPI2
        '21': ST_end_read_en1
        '22': ST_en_buffer1
        '23': ST_GOToWait1
        '24': store_SPI3
        '25': ST_wait_eop1
        '26': store_SPI4
        '27': store_SPI5
        '28': store_SPI6
        '29': ST_end_read_en4
        '30': ST_en_buffer4
        '31': ST_GOToWait4
        '32': store_SPI7
        '33': ST_wait_eop4
        '34': store_SPI8
        '35': store_SPI9
        '36': store_SPI10
        '37': ST_end_read_en5
        '38': ST_en_buffer5
        '39': ST_GOToWait5
        '40': store_SPI11
        '41': ST_wait_eop5
        '42': ST_eth_buffer
        '43': wait_irq
        '44': irq_eth
        '45': store_RB20
        '46': store_RB21
        '47': store_RB22
        '48': store_RB23
        '49': store_RB24
        '50': store_RB25
        '51': ST_endwait
      description_items: 'The Elink rec State Machine      '
    '6':
      sm_name: elink_spi_sm
      file_name: spi_control_sm_fsm
      sm_subindex_items:
        '0': ST_waittoact
        '1': ST_reset
        '2': start
        '3': endinit1
        '4': start1
        '5': st_GPIOA
        '6': st_GPIOA1
        '7': st_GPIOA2
        '8': End_Select
        '9': read_elink_mes1
        '10': Done
        '11': write_elink
        '12': Offset_cal0
        '13': Offset__cal1
        '14': Offset__cal2
        '15': Offset__cal3
        '16': Gain_cal0
        '17': Gain_cal1
        '18': Gain_cal2
        '19': Gain_cal3
        '20': write_csrs7
        '21': write_csrs6
        '22': write_csrs5
        '23': write_csrs4
        '24': write_csrs0
        '25': write_csrs1
        '26': write_csrs2
        '27': ST_Config4
        '28': ST_Config3
        '29': ST_Config1
        '30': ST_Config2
        '31': ST_Rest_2
        '32': ST_Rest_4
        '33': ST_Rest_1
        '34': St_wait
        '35': ST_Rest_RS_1
        '36': ST_Rest_RS_2
        '37': st_GPIOA9
        '38': st_GPIOA10
        '39': st_GPIOA11
        '40': w_busy15
        '41': w_busy16
        '42': w_busy17
        '43': ST_IODIRA0
        '44': w_busy0
        '45': ST_IODIRA1
        '46': w_busy1
        '47': ST_IODIRA2
        '48': w_busy2
        '49': w_busy5
        '50': st_IODIRB1
        '51': st_IODIRB2
        '52': st_IODIRB
        '53': w_busy3
        '54': w_busy4
        '55': w_busy7
        '56': st_GPIOB2
        '57': st_GPIOB1
        '58': w_busy8
        '59': w_busy6
        '60': st_GPIOB0
        '61': st_GPPUA
        '62': w_busy11
        '63': w_busy9
        '64': st_GPPUA2
        '65': st_GPPUA1
        '66': w_busy10
        '67': st_GPPUB1
        '68': w_busy13
        '69': w_busy12
        '70': st_GPPUB2
        '71': w_busy14
        '72': st_GPPUB
        '73': CS_high0
        '74': CS_high1
        '75': CS_high2
        '76': CS_high3
        '77': CS_high4
        '78': CS_high5
        '79': w_busy26
        '80': w_busy27
        '81': w_busy28
        '82': w_busy29
        '83': w_busy30
        '84': w_busy31
        '85': ST_Init_0
        '86': ST_wait_0
        '87': ST_Init_1
        '88': ST_wait_1
        '89': ST_Init_2
        '90': ST_wait_2
        '91': ST_Init_3
        '92': ST_wait_3
        '93': ST_Init_4
        '94': ST_wait_4
        '95': ST_Init_5
        '96': ST_wait_5
        '97': ST_Init_6
        '98': ST_wait_6
        '99': ST_Init_7
        '100': ST_wait_7
        '101': ST_Init_8
        '102': ST_wait_8
        '103': ST_Init_9
        '104': ST_wait_9
        '105': ST_Init_10
        '106': ST_wait_10
        '107': ST_Init_11
        '108': ST_wait_11
        '109': ST_Init_12
        '110': ST_wait_12
        '111': ST_Init_13
        '112': ST_wait_13
        '113': ST_Init_14
        '114': ST_wait_14
        '115': st_Init_2
        '116': ST_wait_15
        '117': ST_Rest_3
        '118': ST_Rest_RS_3
        '119': ST_Rest_RS_4
        '120': St_wait1
        '121': St_wait5
        '122': St_wait6
        '123': St_wait7
        '124': St_wait8
        '125': St_wait9
        '126': St_wait10
        '127': St_wait17
        '128': St_wait18
        '129': St_wait19
        '130': St_wait20
        '131': St_wait32
        '132': St_wait33
        '133': St_wait34
        '134': ST_Config5
        '135': ST_Config6
        '136': St_wait35
        '137': ST_Config7
        '138': St_wait36
        '139': ST_Config8
        '140': St_wait37
        '141': ST_Config9
        '142': St_wait38
        '143': ST_Config10
        '144': St_wait39
        '145': St_wait40
        '146': ST_Config11
        '147': St_wait41
        '148': ST_Config12
        '149': St_wait42
        '150': ST_Config13
        '151': St_wait43
        '152': St_wait44
        '153': ST_Config14
        '154': St_wait45
        '155': ST_Config15
        '156': St_wait46
        '157': ST_Config16
        '158': St_wait47
        '159': St_wait25
        '160': St_wait26
        '161': St_wait27
        '162': St_wait28
        '163': St_wait29
        '164': St_wait30
        '165': St_wait31
        '166': ST_Config17
        '167': St_wait48
        '168': ST_Config18
        '169': St_wait49
        '170': St_wait50
        '171': St_wait51
        '172': ST_Config19
        '173': St_wait52
        '174': ST_Config20
        '175': St_wait53
        '176': St_wait54
        '177': ST_Config21
        '178': St_wait55
        '179': ST_Config22
        '180': St_wait56
        '181': St_wait57
        '182': ST_Config23
        '183': St_wait58
        '184': ST_Config24
        '185': St_wait59
        '186': Break_Loop
        '187': ST_CountRst
        '188': ST_Start_Cnt
        '189': CS_high16
        '190': w_busy43
        '191': st_GPIOA15
        '192': st_GPIOA16
        '193': st_GPIOA17
        '194': w_busy40
        '195': w_busy41
        '196': w_busy42
        '197': CS_high6
        '198': w_busy44
        '199': CS_high17
        '200': w_busy48
        '201': st_GPIOA12
        '202': st_GPIOA13
        '203': st_GPIOA14
        '204': w_busy18
        '205': w_busy19
        '206': w_busy20
        '207': st_GPIOA18
        '208': st_GPIOA19
        '209': st_GPIOA20
        '210': w_busy45
        '211': w_busy46
        '212': w_busy47
        '213': CS_high11
        '214': w_busy49
        '215': CS_high18
        '216': w_busy53
        '217': st_GPIOA21
        '218': st_GPIOA22
        '219': st_GPIOA23
        '220': w_busy21
        '221': w_busy22
        '222': w_busy23
        '223': st_GPIOA24
        '224': st_GPIOA25
        '225': st_GPIOA26
        '226': w_busy50
        '227': w_busy51
        '228': w_busy52
        '229': s0
        '230': s1
        '231': End_Select1
        '232': ST_Read_reg4
        '233': Start_reading
        '234': St_wait64
        '235': ST_Rest_RS_16
        '236': ST_Rest_RS_17
        '237': St_wait66
        '238': ST_Rest_RS_18
        '239': St_wait67
        '240': w_busy55
        '241': St_wait68
        '242': ST_Rest_RS_19
        '243': w_busy57
        '244': w_busy58
        '245': w_busy59
        '246': w_busy60
        '247': s2
        '248': s3
        '249': s4
        '250': s5
        '251': s6
        '252': s7
      description_items: 'The Elink Spi State Machine      '
    '7':
      sm_name: ELink Frames
      file_name: None_sm_s
      sm_subindex_items:
        '0': ST_waittoact
        '1': ST_reset
        '2': ST_start
        '3': ST_endinit
        '4': ST_start
        '5': ST_GPIOA
        '6': ST_GPIOA1
        '7': ST_GPIOA2
        3c: SOF
        dc: EOF
        bc: COMMA
        INVALID: INVALID
      description_items: 'The None State Machine           '
